R/AllClasses.R
R/COTAN-estimators.R
R/COTAN-modifiers.R
R/DEAOnClusters.R
R/GDI-plot.R
R/UMAP-plot.R
R/cellsUniformClustering.R
R/clustersSummaryPlot.R
R/heatmap-plot.R
R/mergeUniformCellsClusters.R
R/utilities.R
tests/testthat/test-AllClasses.R
tests/testthat/test-COTAN-modifiers.R
tests/testthat/test-cellsUniformClustering.R
tests/testthat/test-mergeUniformCellsClusters.R
tests/testthat/test-utilities.R

- All functions returning a clusterization now return an object of type `factor`.
- Clusterizations are now stored as `factor` in the metadataCell `data.frame`
- Added factorToVector() function to enable smooth transitions from `factor` to `character` arrays without loss of names
- Update tests to the new type

Store clusterizations as `factors`

---

R/AllClasses.R

The validity function in AllClasses.R, was checking the genesCoex size with the numGenes variable in the stateman where instead should have checked the cellsCoex size with the numCells variable.

Fix Validity Function in AllClasses.R ~ Paul Magos

---

NEWS.md
R/checkClusterUniformity.R
R/clean-plot.R
man/RawDataCleaning.Rd
tests/testthat/test-establishGenesClusters.R

The flag allows to suppress the evaluation of the *PCA* on the normalised data.
Using this flag, in particular, reduces significantly time spent within the function `checkClusterUniformity()`

Added new flag to the function `cleanPlots()`

---

tests/testthat/test-clean-method.R

The test was failing on non-Intel architectures due to machine precision discrepancies. Now the test allows for tolerances.

Solved issue with test-clean-method.R

---

DESCRIPTION
NEWS.md
R/AllClasses.R
R/COTAN-getters.R
R/COTAN-modifiers.R
R/clustersMarkersHeatmapPlot.R
R/clustersSummaryPlot.R
man/HandlingConditions.Rd
tests/testthat/test-AllClasses.R
tests/testthat/test-COTAN-getters.R
tests/testthat/test-COTAN-modifiers.R

Before it was possible to insert a misaligned clusterization or condition or Coex data-frame,
causing unexpected and obscure errors

Better checks about handling of the clusterizations and the conditions

---

NEWS.md
R/GDI-plot.R
R/cellsUniformClustering.R
R/checkClusterUniformity.R
R/clustersSummaryPlot.R
R/mergeUniformCellsClusters.R
man/HandlingClusterizations.Rd
man/UniformClusters.Rd
tests/outputTestDatasetCreation.R
tests/testthat/test-cellsUniformClustering.R
tests/testthat/test-mergeUniformCellsClusters.R
vignettes/Guided_tutorial_v2.Rmd

Now `COTAN` saves and can use the list of failed merge pairings
Also changed default GDI threshold to 1.43 from the too strict 1.40
Fixed issue with function `clustersTreePlot()`

Now it is possible to properly resume clusters' merges

---

NEWS.md
R/cellsUniformClustering.R
R/checkClusterUniformity.R
R/mergeUniformCellsClusters.R
man/UniformClusters.Rd
tests/testthat/test-cellsUniformClustering.R
tests/testthat/test-mergeUniformCellsClusters.R

From now on it will be possible to recover the results of the `checkUniformCluster()` from dumped .csv files

Added dumping of uniformity check results in clustering functions

---

R/DEAOnClusters.R
R/calculateCoex-method.R
R/cellsUniformClustering.R
R/mergeUniformCellsClusters.R
R/numericUtilities.R
R/reorderClusterization.R
man/HandlingClusterizations.Rd
man/UniformClusters.Rd
tests/testthat/test-cellsUniformClustering.R
tests/testthat/test-mergeUniformCellsClusters.R
vignettes/Guided_tutorial_v2.Rmd

Speed-up of the functions `parallelDispersionBisection()` and `parallelNuBisection()` vias use of `Rfast::rowsums() and `Rfast::colsums()` respectively
Speed-up of function `logFoldChangeOnClusters()` by using overall sum for all clusters instead of calculating out-sums each time
Used `torch::torch_mm()` instead of `torch::torch_matmul()` as it implies less overhead:
it is specialized for 2D tensor multiplications

Speed-up of paramenters estimates (dispersion and nu)

---

NEWS.md
R/utilities.R
vignettes/Guided_tutorial_v2.Rmd

The code that was checking whether the `torch` library is available and ready to use did have a bug causing hard errors.
Now `COTAN` can detect properly whether the `torch` library can be used and in case use it...

Bugfix about torch istallation status checks 

---

NEWS.md
R/cellsUniformClustering.R
R/checkClusterUniformity.R
R/mergeUniformCellsClusters.R
man/UniformClusters.Rd
tests/outputTestDatasetCreation.R
tests/testthat/test-cellsUniformClustering.R
tests/testthat/test-mergeUniformCellsClusters.R
vignettes/Guided_tutorial_v2.Rmd

Up to now the fraction of genes allowed to be above the GDI threshold for uniform clusters was hard-coded to be 1%.
Now it can be set by users if necessary...
Also fixed small bug in reported uniformity checks for cell clustering methods

Allow 'above ratio threshold' as input to cell clustering methods

---

DESCRIPTION
NEWS.md
R/COTAN-getters.R
R/COTAN-modifiers.R
man/CalculatingCOEX.Rd
man/GenesStatistics.Rd
vignettes/Guided_tutorial_v2.Rmd

Now the method `storeGDI()` can take in the output `data.frame` from the function `calculateGDI()`

Improved usability of the method `storeGDI()`

---

DESCRIPTION
R/cellsUniformClustering.R
R/checkClusterUniformity.R
R/mergeUniformCellsClusters.R
R/reorderClusterization.R

It was not working properly when only 1 or 2 clusters were the final clusterization results
Now 'saveObj = FALSE' will avoid touching the file-system in any way: no folders and/or files creation
Bumped up automatic RoxygenNote version

Solved issue with clusterization functions

---

R/automaticCOTANObjectCreation.R
R/cellsUniformClustering.R
R/checkClusterUniformity.R
R/mergeUniformCellsClusters.R

In case of an exception being raised
the call to `dev.off()` was skipped

Avoided issue with pdf file creation

---

NEWS.md
R/establishGenesClusters.R
tests/testthat/test-establishGenesClusters.R

Now `primaryMarkers` argument can be just a single gene

Fixed bug in function `genesCoexSpace()`

---

R/UTCheckers.R

The third check tested that the rank of the threshold was not greater than given input, but this implies that ranked GDI value could exceed given threshold as if rank were 1 greater (unlike given specifications)

Fixed minor bug in AdvancedGDIUniformityCheck

---

NEWS.md
R/AllGenerics.R
R/automaticCOTANObjectCreation.R
man/COTAN_ObjectCreation.Rd

Added possibility to specify `clean()` thresholds in the functions `proceedToCoex()` and `automaticCOTANObjectCreation()`

Clean parameters for `proceedToCoex()`

---

NEWS.md
R/UTCheckers.R
R/clean-plot.R
README.md
man/UniformTranscriptCheckers.Rd
tests/testthat/test-mergeUniformCellsClusters.R

Now it is possible to avoid specifying the checker `class-type` when converting from a `data.frame` representing a checker.

Made more conveninent checkers' conversions

---

NEWS.md
R/numericUtilities.R

The function `parallelDist::parDist()` crashes on Linux aarch64 machines, so it is avoided altogether using the normal `dist()` function

Fixed issue with use of `parallelDist::parDist()`

---

R/cellsUniformClustering.R
tests/testthat/test-COTAN-getters.R

There were differences in the results depending on the usage of `torch` or lack there-of.
Also now the first UMAP plot created during execution of the function `cellsUniformClustering()` will use the first condition in the `COTAN` object if available

Solved test failures

---

NEWS.md
R/AllGenerics.R
R/COTAN-estimators.R
R/DEAOnClusters.R
R/UMAP-plot.R
R/automaticCOTANObjectCreation.R
R/calculateCoex-method.R
R/cellsUniformClustering.R
R/clean-plot.R
R/data.R
R/establishGenesClusters.R
R/findClustersMarkers.R
R/genesStatistics.R
R/heatmap-plot.R
R/mergeUniformCellsClusters.R
man/COTAN_ObjectCreation.Rd
man/Installing_torch.Rd
tests/testthat/test-calculateCoex-method.R

Improved torch `coex` implementation:
- Used more in-place functions
- Avoided use of 2 copies of the entire probability matrix to calculate the probability of zero
Also switched back to `mc.preschedule = TRUE` in all `mclapply()` calls as all sub-tasks take roughly the same amount of time
Added more logging about timings in more numerical intensive functions

Improved torch implementation
